### PR TITLE
Mobile Navigation

### PR DESCRIPTION
**Pull request by Lemonsity**
# Description
- Implement menu for mobile

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by Ynng — CHANGES_REQUESTED** [review]
Nice, works great!
Just a few styling/design suggestions:
- The hamburger button on the right side is hard to awkard to reach, maybe move it to the left instead?
- Maybe? close the menu fully after clicking on a link?

**Comment by msdapptech** [comment]
I reject the first change, simply because that's a use-habit thing, there are people use their phone with right hand

**Comment by Lemonsity** [comment]
I reject the first change because I believe it's a user habit thing. I used to use right hand for phone

**Comment by Lemonsity** [comment]
The second change is resolved now

**Review by Ynng — APPROVED** [review]
Lgtm

**Pull request merged**
