### PR TITLE
fix tools layout with max width and margins

### LINKED ISSUE #2: Improve layout in "Tools Section"
# Intention:
- [x] Add margin between text-blocks
- [x] Add margin to the bottom so we don't enter the footer too early
- [x] Add maximum width of some sort to improve layout on ultra-wide

Don't worry about mobile for now, that is #3

# Why is it necessary:

The amount of time/space allocated for each heading is too little.
As the user scrolls down, the image on the right fades too quickly.

The image also stops being sticky too early, before the last heading is even in the middle of the screen.

This is what it looks like right now.

image

### PR DESCRIPTION
**Pull request by pinnouse**
merge changes for #2 in tools section

- added '.subcontainer' to have a max-width for the content
- increased margins

### CODE REVIEW

**Comment by Ynng** [comment]
looking good on ultrawide! there's not enough space between text though

sorry I wasn't really clear with the reason for change
This is what I meant by margin between text
image

and this is what I meant by "margin at the bottom" (the sticky image is losing its sticky affect too early, its matching text block is only in the middle of the page)
image



here's the design of the page in figma for reference
https://www.figma.com/files/project/54356993/website-design?fuid=764610386209118104

and here's an example of what we wante
https://web.archive.org/web/20211007202129/https://webflow.com/nocodeconf

**Comment by pinnouse** [comment]
@Ynng 
How's this?
lodestone

Or would you rather me remove the top margin of the first point?

**Comment by Ynng** [comment]
I like this
I don't think extra margin is needed

**Review by Ynng — APPROVED** [review]
Looks good to me!

**Pull request merged**
